### Logistic Regression Exercise

In [30]:
# import numpy
import numpy as np

# import linear_model and datasets from sklearn
from sklearn import linear_model, datasets

# import GridSearchCV from sklearn
from sklearn.model_selection import GridSearchCV

In [31]:
# Load data
iris = datasets.load_iris()
X = iris.data
y = iris.target

* print the shape of X

In [32]:
X.shape

(150, 4)

In [33]:
X[0] # let's scale this, why not

array([5.1, 3.5, 1.4, 0.2])

* print y

In [34]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [35]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scale = scaler.fit_transform(X)

In [36]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_scale,y,test_size=0.25,random_state=0)

* create a logistic regression model
    - **Note:** Spend some time on the logistic regression documentation to get familiar with the available parameters.

In [37]:
model = linear_model.LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [51]:
param_grid = {
    'penalty': ['l1','l2','elasticnet','none'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]
}

* create a regularization space for the **'penalty'** parameter (a.k.a. what values do we want to insert into our GridSearch?)

In [49]:
#above

* create a regularization space for the **'c'** parameter (a.k.a. what values do we want to insert into our GridSearch?)

In [50]:
#above

* create a hyperparameter options dictionary

In [17]:
#mhm

* create a grid search using 5-fold cross validation

In [52]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, 
                    cv=5, 
                    scoring='accuracy',
                    verbose=1, 
                    n_jobs=-1)

* fit the grid search

In [53]:
grid_result = grid.fit(X_train,y_train)

Fitting 5 folds for each of 28 candidates, totalling 140 fits


/Users/louisrossi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.69644269        nan 0.96403162        nan 0.81264822
        nan 0.96403162        nan 0.89407115        nan 0.96403162
        nan 0.94664032        nan 0.96403162        nan 0.96403162
        nan 0.96403162        nan 0.96442688        nan 0.96403162
        nan 0.95533597        nan 0.96403162]
  warnings.warn(


* take the best model from grid search

In [41]:
best_model = grid_result.best_estimator_

* print the best hyperparameters

In [56]:
grid_result.best_params_

{'C': 100, 'penalty': 'l2'}

In [43]:
best_hp = grid_result.best_score_
best_hp

0.9644268774703558

* predict the target vector
    - class ( *predict* )
    - probabilities ( *predict_proba* )

In [44]:
y_pred = best_model.predict(X_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [45]:
y_pred_proba = best_model.predict_proba(X_test)

In [46]:
y_pred_proba[0] # ...

array([3.65410987e-12, 2.02000760e-05, 9.99979800e-01])

- plot the ROC curve and print the AUC

In [43]:
from sklearn import metrics

In [51]:
# value_error: y needs to be binary
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

# Plot not working (need y as binary)

In [50]:
fpr,tpr, _ = metrics.roc_curve(y_test, y_pred_proba)
auc = metrics.roc_auc_score(y_test, y_pred_proba)
plt.plot(fpr,tpr)
plt.legend(loc=4)
plt.show()

ValueError: multiclass format is not supported

* print the Logreg coeficients

In [47]:
print(best_model.coef_)

[[-2.21460247  2.66167029 -6.1247489  -5.47036649]
 [ 2.63220956 -0.36121549 -4.96648518 -0.99251977]
 [-0.41760708 -2.3004548  11.09123408  6.46288627]]


* print the Logreg intercepts

In [48]:
print(best_model.intercept_)

[ 0.82434282  6.85294867 -7.67729149]
